FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    python3-pip \
    python3-wheel \
    python3-setuptools \
    git \
    cmake \
    libblas3 \
    libblas-dev \
    build-essential \
    gcc \
    && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

ENV HOME="/home/jovyan"
RUN mkdir $HOME && chmod 0777 $HOME

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		vim htop ssh wget curl fonts-takao-pgothic fonts-takao-mincho \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install pip -U
RUN pip3 install \
  chainer==6.2.0 \
  cupy-cuda100==6.2.0 \
  gin-config==0.1.4 \
  disentanglement-lib==1.2 \
  matplotlib==3.0.3 \
  numpy==1.16.3 \
  pandas==0.24.2 \
  Pillow==6.0.0 \
  tensorflow-gpu==1.13.1 \
  tensorflow-probability==0.6.0 \
  && rm -rf /root/.cache